# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_paginate}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marco Scholl"]
  s.date = %q{2011-02-15}
  s.description = %q{a new rails 3 paginate plugin as will_paginate replacement}
  s.email = %q{develop@marco-scholl.de}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/rails_paginate.rb",
    "lib/rails_paginate/collection.rb",
    "lib/rails_paginate/core_ext/active_record.rb",
    "lib/rails_paginate/core_ext/array.rb",
    "lib/rails_paginate/method.rb",
    "lib/rails_paginate/method/base.rb",
    "lib/rails_paginate/method/jumping.rb",
    "lib/rails_paginate/method/sliding.rb",
    "lib/rails_paginate/renderer.rb",
    "lib/rails_paginate/renderer/base.rb",
    "lib/rails_paginate/renderer/html_default.rb",
    "lib/rails_paginate/renderer/html_list.rb",
    "spec/db/migrate/20110215200000_create_items.rb",
    "spec/rails_paginate_spec.rb",
    "spec/renderer_html_default_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/10_activerecord.rb"
  ]
  s.homepage = %q{http://github.com/phatworx/rails_paginate}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{a new rails 3 paginate plugin}
  s.test_files = [
    "spec/db/migrate/20110215200000_create_items.rb",
    "spec/rails_paginate_spec.rb",
    "spec/renderer_html_default_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/10_activerecord.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<autotest>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<autotest>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<autotest>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

